### ISSUE TITLE
css变量

### ISSUE THREAD

**Issue by h266094** [h266094/blog#1]
> 声明变量的时候，变量名前面要加两根连词线（--）

```css
body {
  --foo: #7f583f;
  --bar: #f7efd2;
}
```

变量名大小写敏感，--header-color和--Header-Color是两个不同变量。

> var()函数用于读取变量

```css
:root {
  --primary-color: red;
  --logo-text: var(--primary-color);
}
```
